@startuml contexto-geral

'acrescentar camada de borda envolvendo autorizacao e gateway

!include <c4/C4_Container.puml>

SHOW_PERSON_OUTLINE()

System(sistema_clinica, "Sistema da Clínica", "Agendamento de consultas e registro de atendimentos clínicos")

System_Ext(sesgo, "Plataforma de Interoperabilidade de Saúde", "Recebe/fornece informações clínicas")

Person(recepcionista, "Recepcionista", "Responsável pelo registro de agendamentos")
Person(profissional, "Profissional de Saúde", "Reponsável pelo atendimento clínico e registro das informações pertinentes")

Rel(recepcionista, sistema_clinica, "Gestão de agendamentos", "Web App")
Rel(profissional, sistema_clinica, "Registro e consulta de informações clínicas", "Web App")

BiRel(sistema_clinica, sesgo, "Padrão FHIR")

@enduml